"""Regenerate the exact package pins in the ``workbench`` extra of pyproject.toml.

The student launchers install ``flightlab[workbench]`` from the promoted Git
commit and take whatever versions PyPI offers at that moment.  To keep every
student on identical libraries for the whole semester, the ``workbench`` extra
is a complete list of exact versions, resolved once for Windows, macOS, and
Linux on Python 3.12.  This script produces that list from the loose inputs:

* the core ``dependencies`` in ``pyproject.toml``
* ``student_setup/workbench.in``

Run it once a year before the course starts (or whenever a library must move):

    python student_setup/update_pins.py

To add or remove a package mid-semester without moving any other pin, pass
``--keep``; every package already pinned stays at its current version and only
the new requirement is resolved:

    python student_setup/update_pins.py --keep

It needs ``uv`` on the PATH (https://docs.astral.sh/uv/ or ``pip install uv``).
Then run the test suite and the workbench once, commit, and promote the commit
in ``student_setup/release.txt`` as usual.
"""

from __future__ import annotations

from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
PYPROJECT = ROOT / "pyproject.toml"
WORKBENCH_IN = ROOT / "student_setup" / "workbench.in"
PYTHON_VERSION = "3.12"  # the launchers install this interpreter
BEGIN = "    # BEGIN PINS (generated by student_setup/update_pins.py; do not edit by hand)\n"
END = "    # END PINS\n"


def current_pins(text: str) -> list[str]:
    """Return the ``name==version ; marker`` requirements now in pyproject.toml."""
    start = text.find(BEGIN) + len(BEGIN)
    stop = text.find(END)
    return [
        match.group(1)
        for match in re.finditer(r'^\s*"([^"]+)",', text[start:stop], flags=re.MULTILINE)
    ]


def resolve(uv: str, constraints: list[str] | None = None) -> list[str]:
    """Return the resolved requirement lines, one per package.

    With ``constraints``, the listed requirements are passed to the resolver as
    constraints and ``--upgrade`` is omitted, so already-pinned packages keep
    their versions and only unpinned requirements are resolved.
    """
    command = [
        uv, "pip", "compile",
        str(PYPROJECT), str(WORKBENCH_IN),
        "--universal",
        "--python-version", PYTHON_VERSION,
        "--no-header",
        "--annotation-style", "line",
        "--quiet",
    ]
    with tempfile.TemporaryDirectory() as folder:
        if constraints is None:
            command.append("--upgrade")
        else:
            constraint_file = Path(folder) / "constraints.txt"
            constraint_file.write_text("".join(f"{line}\n" for line in constraints))
            command += ["--constraint", str(constraint_file)]
        output = subprocess.run(command, check=True, capture_output=True, text=True, cwd=ROOT).stdout
    return [line.rstrip() for line in output.splitlines() if line.strip() and not line.startswith("#")]


def to_toml(lines: list[str]) -> str:
    """Turn ``name==1.2 ; marker  # via x`` lines into quoted TOML array items."""
    items = []
    for line in lines:
        requirement, _, comment = line.partition("#")
        requirement = " ".join(requirement.split())
        if "==" not in requirement:
            raise SystemExit(f"unpinned requirement in resolver output: {line}")
        item = f'    "{requirement}",'
        # Drop the temporary constraints file that ``--keep`` passes to uv from
        # the "via" annotation; it is not a real requirement source.
        sources = [
            source.strip() for source in comment.replace("via ", "", 1).split(",")
            if source.strip() and not source.strip().startswith("-c ")
        ]
        if sources:
            item += f"  # via {', '.join(sources)}"
        items.append(item + "\n")
    return "".join(items)


def main() -> None:
    uv = shutil.which("uv")
    if uv is None:
        raise SystemExit("uv was not found on the PATH; install it with `pip install uv` and rerun.")

    text = PYPROJECT.read_text()
    start = text.find(BEGIN)
    stop = text.find(END)
    if start < 0 or stop < 0 or stop < start:
        raise SystemExit("pyproject.toml is missing the BEGIN PINS / END PINS markers.")

    keep = "--keep" in sys.argv[1:]
    pins = to_toml(resolve(uv, current_pins(text) if keep else None))
    updated = text[: start + len(BEGIN)] + pins + text[stop:]
    if updated == text:
        print("pyproject.toml already matches the current resolution.")
        return
    PYPROJECT.write_text(updated)
    print(f"Updated the workbench pins in pyproject.toml ({len(pins.splitlines())} packages). "
          "Run the tests and the workbench, then commit.")

if __name__ == "__main__":
    sys.exit(main())
